spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: mysqladmin
    url: jdbc:mysql://127.0.0.1/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
#  返回的json参数，如果参数为空，则该参数返回给前端
  jackson:
    default-property-inclusion: non_null
  redis:
    host: 192.168.121.186
    port: 6379
server:
#  context-path: /sell
  port: 8099
#微信公众号的id和secert
wechat:
  mpAppid: wxfc26418b74dcb0a8
  mpAppSecert: fadb448b94aa080266315a3607b689ea
  #借用的支付账号
  mcMpAppid: wxd898fcb01713c658
  mcMpAppSecert: fadb448b94aa080266315a3607b689ea
  mchId: 1483469312
  mchKey: C5245D70627C1F8E9964D494B0735025
  keyPath: G:\学习\微信授权付款\微信支付\h5.p12
  notifyUrl: http://sellweb.natapp1.cc/pay/notify
  #微信开放平台的openid
  openAppId: wx6ad144e54af67d87
  openAppSecret: 91a2ff6d38a2bbccfb7e9f9079108e2e
#项目对应URL
projectUrl:
  wechatMpAuthorize: http://sellweb.natapp1.cc
  wechatOpenAuthorize: http:/sellweb.natapp1.cc
  sell: http://sellweb.natapp1.cc

#logging:
#  pattern:
#    #  日志+内容+换行
#    console: "%d -%msg%n"
#   #默认的日志文件名称为spring.log
#  file: "E:/logs/sell/sell.log"
#  #没效果？？
#  level: debug
#  com.imooc.LoggerTest: debug
#  com.imooc: debug